stages:
  - build
  - deploy

variables:
  KUBECONFIG: $FILE_BASE

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd backend
    - docker build -t $DOCKER_REGISTRY_URL .
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
    - docker push $DOCKER_REGISTRY_URL

deploy:
  stage: deploy
  image: bitnami/kubectl
  script:
    - kubectl config use-context context --kubeconfig=$FILE_BASE
    - cd k8s
    - cd node
    - kubectl apply -f node-deployment.yml && kubectl apply -f node-service.yml
    - cd ../mongo
    - kubectl apply -f mongo-secrets.yml && kubectl apply -f mongo-rules.yml && kubectl apply -f mongo-statefulset.yml && kubectl apply -f mongo-service.yml
    - cd ../redis
    - kubectl apply -f redis-config.yml && kubectl apply -f redis-pod.yml && kubectl apply -f redis-svc.yml
    - cd ../rabbitmq
    - kubectl apply -f rabbitmq-statefulset.yml && kubectl apply -f rabbitmq-svc.yml
