apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: "do-block-storage"
  accessModes:
  - ReadWriteOnce 
  volumeName: pv
  resources:
    requests:
      storage: 1Gi